sudo: required

services:
  - docker

language: java
jdk: openjdk10

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # AUTH SERVICE
  - export AUTH=shaldnikita/moneycontrol-auth-service
  - docker build -t $AUTH:$COMMIT ./auth-service
  - docker tag $AUTH:$COMMIT $AUTH:$TAG
  - docker push $AUTH

  # CONFIG SERVICE
  - export CONFIG=shaldnikita/moneycontrol-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=shaldnikita/moneycontrol-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=shaldnikita/moneycontrol-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # COSTS SERVICE
  - export COSTS=shaldnikita/moneycontrol-costs-service
  - docker build -t COSTS:$COMMIT ./costs-service
  - docker tag COSTS:$COMMIT COSTS:$TAG
  - docker push $COSTS

# CASHSPENDER SERVICE
  - export CASHSPENDER=shaldnikita/moneycontrol-cashspender
  - docker build -t CASHSPENDER:$COMMIT ./cashspender
  - docker tag CASHSPENDER:$COMMIT CASHSPENDER:$TAG
  - docker push $CASHSPENDER