sudo: required

services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # AUTH SERVICE
  - export AUTH=shaldnikita/homeproject-auth-service
  - docker build -t $AUTH:$COMMIT ./auth-service
  - docker tag $AUTH:$COMMIT $AUTH:$TAG
  - docker push $AUTH

  # BOOKSTORE SERVICE
  - export BOOKSTORE=shaldnikita/homeproject-bookstore
  - docker build -t $BOOKSTORE:3$COMMIT ./bookstore
  - docker tag $BOOKSTORE:$COMMIT $BOOKSTORE:$TAG
  - docker push $BOOKSTORE

  # READERS SERVICE
  - export READERS=shaldnikita/homeproject-readers-service
  - docker build -t READERS:$COMMIT ./readers-service
  - docker tag READERS:$COMMIT READERS:$TAG
  - docker push READERS

  # LIBRARY
  - export LIBRARY=shaldnikita/homeproject-library
  - docker build -t LIBRARY:$COMMIT ./library
  - docker tag LIBRARY:$COMMIT LIBRARY:$TAG
  - docker push LIBRARY

  # CONFIG SERVICE
  - export CONFIG=shaldnikita/homeproject-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=shaldnikita/homeproject-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=shaldnikita/homeproject-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY