version: '2.3'

services:
  rabbitmq:
      image: rabbitmq:3-management
      restart: always
      ports:
        - 15672:15672
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  config:
      environment:
        CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      image: shaldnikita/homeproject-config
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: shaldnikita/homeproject-registry
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: shaldnikita/homeproject-gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: shaldnikita/homeproject-monitoring
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 9000:8080
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"