version: '2.1'

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: user
      MYSQL_PASSWORD: changeme
      MYSQL_DATABASE: homeproject

  adminer:
    image: adminer
    restart: always
    ports:
    - 80:8080