version: '2.1'

services:

  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_DB: homeproject
      POSTGRES_USER: user
      POSTGRES_PASSWORD: changeme
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080