eureka.client.enabled: false

logging.level.org.springframework.*: DEBUG

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/auth/users/current

auth-service: localhost:5000/auth
registry: localhost:8761/registry
gateway: localhost:4000
library: localhost:9000/library
bookstore-service: localhost:7000/bookstore