eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service/auth/users/current

auth-service: auth-service/auth
registry: registry/registry
gateway: gateway
library: library/library
bookstore-service: bookstore/bookstore