server:
  servlet:
    context-path: /auth
  port: ${PORT:5000}

spring.jpa:
  hibernate:
    ddl-auto: create
    use-new-id-generator-mappings: true
  datasource:
      url: jdbc:mysql://auth-mysql:3306/home_project
      password: ${MYSQL_PASSWORD}
