server:
  servlet:
    context-path: /auth
  port: ${PORT:5000}

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show_sql: true
    hibernate:
      ddl-auto: create
      show_sql: true
      use-new-id-generator-mappings: true
---
spring.profiles: default

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeproject
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:changeme}

---
spring.profiles: prod

spring:
  datasource:
    url: jdbc:postgresql://auth-postgresql:5432/homeproject
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:changeme}

