server:
  servlet:
    context-path: /auth
  port: ${PORT:5000}

---
spring.profiles: default

eureka.client.enabled: false

spring.jpa:
  hibernate:
    ddl-auto: create
    use-new-id-generator-mappings: true
  datasource:
    url: jdbc:mysql://localhost:3306/home_project
    user: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:changeme}

---
spring.profiles: prod

eureka.client.enabled: true

spring.jpa:
  hibernate:
    ddl-auto: create
    use-new-id-generator-mappings: true
  datasource:
    url: jdbc:mysql://auth-mysql:3306/home_project
    user: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:changeme}

