server:
  servlet:
    context-path: /bookstore
  port: ${PORT:7000}

spring.jpa:
  hibernate:
    ddl-auto: validate
    use-new-id-generator-mappings: true

spring.datasource:
  url: jdbc:mysql://localhost:3306/home_project
  username: sn1
  password: sn1

# disable actuagor security for endpoints
management:
  security:
    enabled: false
