server:
  servlet:
    context-path: /bookstore
  port: ${PORT:7000}

spring.jpa:
  hibernate:
    ddl-auto: create
    use-new-id-generator-mappings: true

spring.datasource:
  url: jdbc:mysql://bookstore-mysql:3306/home_project
  password: ${MYSQL_PASSWORD}

# disable actuagor security for endpoints
management:
  security:
    enabled: false
