server:
  servlet:
    context-path: /bookstore
  port: ${PORT:7000}

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show_sql: true
    hibernate:
      ddl-auto: create
      show_sql: true
      use-new-id-generator-mappings: true

---
spring.profiles: prod

spring:
  datasource:
    url: jdbc:postgresql://bookstore-postgresql:5432/homeproject
    username: $(POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:changeme}

security:
  oauth2:
    client:
      clientId: bookstore
      clientSecret: changeme
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

---
spring.profiles: default

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeproject
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:changeme}

security:
  oauth2:
    client:
      clientId: bookstore
      clientSecret: changeme
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server