ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    bookstore:
      path: /**
      serviceId: bookstore
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 5000
