server:
  port: 5000

spring:
  application:
    name: gateway

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
     connect-timeout-millis: 20000
     socket-timeout-millis: 20000

  routes:
    bookstore-service:
      path: /bookstore/**
      serviceId: bookstore
      stripPrefix: false
      sensitiveHeaders:
