server:
  port: 4000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /auth/**
      url: auth-service
      stripPrefix: false
      sensitiveHeaders:

    bookstore:
      path: /bookstore/**
      serviceId: bookstore
      stripPrefix: false
      sensitiveHeaders:

