server:
  servlet:
    context-path: /library
  port: ${PORT:9000}


---
spring.profiles: prod

security:
  oauth2:
    client:
      clientId: library
      clientSecret: changeme
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      userAuthorizationUri: http://auth-service:5000/auth/oauth/authorize
    resource:
      userInfoUri: http://auth-service:5000/auth/current

---
spring.profiles: default

security:
  oauth2:
    client:
      clientId: 244746426198019
      clientSecret: ${FACEBOOK_SECRET}
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me

