server:
  servlet:
    context-path: /readers
  port: 6000

---
spring.profiles: default

auth-service.url: localhost:5000

security:
  oauth2:
    client:
      clientId: readers-service
      clientSecret: changeme
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: Readers

---
spring.profiles: prod

auth-service.url: auth-service

security:
  oauth2:
    client:
      clientId: readers-service
      clientSecret: changeme
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: readers-mongodb
      username: $(MONGO_PASSWORD:user}
      password: ${MONGO_PASSWORD:changeme}
      database: Readers
      port: 27017

