server:
  servlet:
    context-path: /users
  port: 8500

---
spring.profiles: default

security:
  oauth2:
    client:
      clientId: users-service
      clientSecret: changeme
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: Readers

---
spring.profiles: prod

auth-service.url: auth-service

security:
  oauth2:
    client:
      clientId: users-service
      clientSecret: changeme
      accessTokenUri: http://auth-service:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: users-mongodb
      username: $(MONGO_PASSWORD:}
      password: ${MONGO_PASSWORD:}
      database: Readers
      port: 27017

